=== Limro/IHA/WEBT/Workspace/Week2/xmlValidator/src/stamtrae.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="person" type="personType"/>

    <xs:complexType name="parentType">
        <xs:sequence>
            <xs:element ref="person" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personType">
        <xs:all>
            <xs:element name="mother" type="parentType"/>
            <xs:element name="father" type="parentType"/>
        </xs:all>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
</xs:schema>

=== Limro/IHA/WEBT/Workspace/Week2/xmlValidator/src/stamtrae.xml
<person name="John Doe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="stamtrae.xsd">
	<!-- <uncle></uncle> -->

  <father>
    <person name="John Doe's father">
      <father>
        <person name="John Doe's father's father">
          <father>
            <person name="John Doe's father's father's father">
              <father/>
              <mother/>
            </person>
          </father>
          <mother>
            <person name="John Doe's father's father's mother">
              <father/>
              <mother/>
            </person>
          </mother>
        </person>
      </father>
      <mother>
        <person name="John Doe's father's mother">
          <father>
            <person name="John Doe's father's mother's father">
              <father/>
              <mother/>
            </person>
          </father>
          <mother>
            <person name="John Doe's father's mother's mother">
              <father/>
              <mother/>
            </person>
          </mother>
        </person>
      </mother>
    </person>
  </father>
  <mother>
    <person name="John Doe's mother">
      <father>
        <person name="John Doe's mother's father">
          <father>
            <person name="John Doe's mother's father's father">
              <father/>
              <mother/>
            </person>
          </father>
          <mother>
            <person name="John Doe's mother's father's mother">
              <father/>
              <mother/>
            </person>
          </mother>
        </person>
      </father>
      <mother>
        <person name="John Doe's mother's mother">
          <father>
            <person name="John Doe's mother's mother's father">
              <father/>
              <mother/>
            </person>
          </father>
          <mother>
            <person name="John Doe's mother's mother's mother">
              <father/>
              <mother/>
            </person>
          </mother>
        </person>
      </mother>
    </person>
  </mother>
</person>
